version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng-dev
    ports:
      - "8080:8080"
    volumes:
      - ./searxng-settings.yml:/etc/searxng/settings.yml:ro
      - ./limiter.toml:/etc/searxng/limiter.toml:ro
      - searxng-data:/var/log/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=super-secret-key-for-development-only
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - searxng-network

  redis:
    image: redis:7-alpine
    container_name: searxng-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - searxng-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  searxng-data:
  redis-data:

networks:
  searxng-network:
    driver: bridge